#!/bin/zsh

# Run the Python code inline
python3 - "$@" << 'EOF'
import os
import argparse

def find_zshrc():
    home_dir = os.path.expanduser("~")
    zshrc = os.path.join(home_dir, ".zshrc")

    if not os.path.exists(zshrc):
        return None
    return zshrc

def append_alias(alias, command):
    zshrc = find_zshrc()

    with open(zshrc, "a") as zshrc_file:
        zshrc_file.write(f'\nalias {alias}="{command}"\n')

def remove_alias(alias):
    zshrc = find_zshrc()
    with open(zshrc, 'r') as file:
        lines = file.readlines()

    without_alias = [line for line in lines if not line.strip().startswith(f'alias {alias}=')]

    with open(zshrc, 'w') as file:
        file.writelines(without_alias)

def get_args():
    parser = argparse.ArgumentParser(description="Create aliases quickly.")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--add",
                        nargs=2,
                        metavar=('ALIAS', 'COMMAND'),
                        help="Used to create an alias with two following arguments." \
                        " e.g. `ali --add <alias> <command>\n" \
                        "Ensure the <command> arg is a string")
    group.add_argument("--remove",
                        nargs=1,
                        metavar='ALIAS',
                        help="Used to remove an alias from .zshrc." \
                        " e.g. `ali --remove <alias>")
    return parser.parse_args()

def main():
    import sys
    try:
        args = get_args()
    except SystemExit as e:
        if e.code == 0:
            sys.exit(1)
        else:
            sys.exit(e.code)

    if args.add:
        alias = args.add[0]
        command = args.add[1]
        append_alias(alias, command)
        
    elif args.remove:
        alias = args.remove[0]
        remove_alias(alias)


if __name__ == "__main__":
    import sys
    sys.exit(main())
EOF

if [ $? -eq 0 ]; then
    source ~/.zshrc
    echo "Alias updated."
fi
